export const lettersAllowed = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

export const WordsList = [
    'aide',
    'chef',
    'enfant',
    'garde',
    'gauche',
    'geste',
    'gosse',
    'livre',
    'merci', 
    'mort',
    'ombre',
    'part',
    'poche',
    'professeur',
    'tour',
    'fois',
    'madame',
    'paix',
    'voix',
    'affaire',
    'arme',
    'attention',
    'balle',
    'bouche',
    'carte',
    'cause',
    'chambre',
    'chance',
    'chose',
    'classe',
    'confiance',
    'couleur',
    'cour',
    'cuisine',
    'dame',
    'dent',
    'droite',
    'envie',
    'erreur',
    'face',
    'faim',
    'famille',
    'faute',
    'femme',
    'fille',
    'fleur',
    'force',
    'forme',
    'guerre',
    'gueule',
    'habitude',
    'heure',
    'histoire',
    'image',
    'impression',
    'jambe',
    'joie',
    'langue',
    'lettre',
    'ligne',
    'main',
    'maison',
    'maman',
    'marche',
    'merde',
    'minute',
    'musique',
    'nuit',
    'odeur',
    'oreille',
    'parole',
    'partie',
    'peau',
    'peine',
    'personne',
    'peur',
    'photo',
    'pierre',
    'place',
    'police',
    'porte',
    'prison',
    'putain',
    'question',
    'raison',
    'robe',
    'route',
    'salle',
    'seconde',
    'semaine',
    'situation',
    'soeur',
    'sorte',
    'suite',
    'table',
    'terre',
    'ville',
    'voiture',
    'avis',
    'bois',
    'bras',
    'choix',
    'corps',
    'cours',
    'gars',
    'mois',
    'pays',
    'prix',
    'propos',
    'sens',
    'temps',
    'travers',
    'vieux',
    'accord',
    'agent',
    'amour',
    'appel',
    'arbre',
    'argent',
    'avenir',
    'avion',
    'bateau',
    'besoin',
    'bonheur',
    'bonjour',
    'bord',
    'boulot',
    'bout',
    'bruit',
    'bureau',
    'camp',
    'capitaine',
    'chat',
    'chemin',
    'cheval',
    'cheveu',
    'chien',
    'ciel',
    'client',
    'coin',
    'colonel',
    'compte',
    'copain',
    'coup',
    'courant',
    'dieu',
    'docteur',
    'doigt',
    'dollar',
    'doute',
    'droit',
    'effet',
    'endroit',
    'ennemi',
    'escalier',
    'esprit',
    'exemple',
    'fait',
    'film',
    'flic',
    'fond',
    'front',
    'genre',
    'gouvernement',
    'grand',
    'groupe',
    'haut',
    'homme',
    'honneur',
    'instant',
    'jardin',
    'jour',
    'journal',
    'lieu',
    'long',
    'mari',
    'mariage',
    'matin',
    'milieu',
    'million',
    'moment',
    'monde',
    'monsieur',
    'mouvement',
    'moyen',
    'ir',
    'uveau',
    'oeil',
    'oiseau',
    'oncle',
    'ordre',
    'papa',
    'papier',
    'parent',
    'passage',
    'patron',
    'petit',
    'peuple',
    'pied',
    'plaisir',
    'plan',
    'point',
    'pouvoir',
    'premier',
    'prince',
    'quartier',
    'rapport',
    'regard',
    'reste',
    'retard',
    'retour',
    'revoir',
    'salut',
    'sang',
    'secret',
    'seigneur',
    'sentiment',
    'service',
    'seul',
    'signe',
    'silence',
    'soir',
    'soldat',
    'soleil',
    'sourire',
    'souvenir',
    'sujet',
    'tout',
    'train',
    'travail',
    'trou',
    'truc',
    'type',
    'vent',
    'ventre',
    'verre',
    'village',
    'visage',
    'voyage',
    'fils',
    'gens']

export const allowedInput = [
    {id : 65, name : 'A'},
    {id : 66, name : 'B'},
    {id : 67, name : 'C'},
    {id : 68, name : 'D'},
    {id : 69, name : 'E'},
    {id : 70, name : 'F'},
    {id : 71, name : 'G'},
    {id : 72, name : 'H'},
    {id : 73, name : 'I'},
    {id : 74, name : 'J'},
    {id : 75, name : 'K'},
    {id : 76, name : 'L'},
    {id : 77, name : 'M'},
    {id : 78, name : 'N'},
    {id : 79, name : 'O'},
    {id : 80, name : 'P'},
    {id : 81, name : 'Q'},
    {id : 82, name : 'R'},
    {id : 83, name : 'S'},
    {id : 84, name : 'T'},
    {id : 85, name : 'U'},
    {id : 86, name : 'V'},
    {id : 87, name : 'W'},
    {id : 88, name : 'X'},
    {id : 89, name : 'Y'},
    {id : 90, name : 'Z'},
    {id : 13, name : 'enter'},
    {id : 27, name : 'escape'},
    ]

